$filePath = 'app\src\screens\Chat\ChatScreen.js'
$content = [System.IO.File]::ReadAllText($filePath)

$oldBlock = "  useEffect(() => {`r`n    activeConvIdRef.current = activeConvId;`r`n    if (activeConvId && conversations.length > 0) {`r`n      const conv = conversations.find(c => c.id === activeConvId);`r`n      if (conv && conv.participants?.length > 0) {`r`n        const participant = conv.participants.find(p => p.id !== currentUser.id);`r`n        if (participant) {`r`n          setParticipantDetails({`r`n            userName: participant.fullName || participant.phone || 'User',`r`n            receiverId: participant.id,`r`n            avatar: participant.avatar,`r`n            otherParticipant: participant,`r`n          });`r`n        }`r`n      }`r`n    }`r`n  }, [activeConvId, conversations, currentUser.id]);`r`n`r`n  // Fetch participant profile if not loaded from context`r`n  useEffect(() => {`r`n    const shouldFetchParticipant = !userName && receiverId && !participantDetails.otherParticipant;`r`n    if (shouldFetchParticipant) {`r`n      api.get(`/users/${receiverId}/profile`)`r`n        .then((res) => {`r`n          const userData = res.data.data;`r`n          setParticipantDetails(prev => ({`r`n            ...prev,`r`n            userName: userData?.fullName || userData?.phone || 'User',`r`n            avatar: userData?.avatar || prev.avatar,`r`n            otherParticipant: userData,`r`n          }));`r`n        })`r`n        .catch((error) => {`r`n          console.log('Error fetching participant profile:', error.message);`r`n        });`r`n    }`r`n  }, [receiverId, userName]);"

$newBlock = "  // Keep activeConvIdRef in sync`r`n  useEffect(() => {`r`n    activeConvIdRef.current = activeConvId;`r`n  }, [activeConvId]);`r`n`r`n  // Always fetch full participant details from the conversation endpoint on mount.`r`n  // This guarantees otherParticipant.role and providerProfile are populated regardless`r`n  // of how the chat was opened (provider profile page vs. Messages list).`r`n  useEffect(() => {`r`n    if (!activeConvId) return;`r`n`r`n    api.get(`/chat/conversations/${activeConvId}`)`r`n      .then((res) => {`r`n        const conv = res.data.data;`r`n        if (!conv?.participants) return;`r`n        const other = conv.participants.find((p) => p.userId !== currentUser.id);`r`n        if (!other?.user) return;`r`n        const u = other.user;`r`n        setParticipantDetails({`r`n          userName: u.fullName || u.phone || 'User',`r`n          receiverId: u.id,`r`n          avatar: u.avatar || '',`r`n          otherParticipant: u,`r`n        });`r`n      })`r`n      .catch((err) => {`r`n        console.log('[ChatScreen] Could not fetch conversation details:', err.message);`r`n        // Fallback: try to find participant in already-loaded conversations context`r`n        if (conversations.length > 0) {`r`n          const conv = conversations.find((c) => c.id === activeConvId);`r`n          if (conv?.participants?.length > 0) {`r`n            const participant = conv.participants.find((p) => p.id !== currentUser.id);`r`n            if (participant) {`r`n              setParticipantDetails({`r`n                userName: participant.fullName || participant.phone || 'User',`r`n                receiverId: participant.id,`r`n                avatar: participant.avatar || '',`r`n                otherParticipant: participant,`r`n              });`r`n            }`r`n          }`r`n        }`r`n      });`r`n  // eslint-disable-next-line react-hooks/exhaustive-deps`r`n  }, [activeConvId]);"

if ($content.Contains($oldBlock)) {
    $result = $content.Replace($oldBlock, $newBlock)
    [System.IO.File]::WriteAllText($filePath, $result)
    Write-Host 'SUCCESS'
} else {
    Write-Host 'NOT FOUND'
    Write-Host "Content length: $($content.Length)"
}
